version: "3.3"

services:

  nginx:
    image: 'nginx'
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-selfsigned.key:/etc/nginx/certificates/cert.key
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/certificates/cert.crt
    depends_on:
      - fpm-odyssey
      - redis
      - db

  fpm-odyssey:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "127.0.0.1:9000:9000"
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html:cached
    depends_on:
      - redis
      - db

  redis:
    image: redis
    container_name: redis_cache
    volumes:
      - redis_data:/var/lib/redis
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - "127.0.0.1:6379:6379"

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MAX_CONNECTIONS=${MAX_SQL_CONN}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3333:3306"

volumes:
  redis_data:
    external: true

  mariadb_data:
    external: true

